services:
  telegram-bot-api:
    build: .
    image: luizhanauer/telegram-bot-api:latest
    container_name: telegram-bot-api
    restart: always
    env_file: .env
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - PUID=1000  # Opcional: define qual usuário será o dono dos arquivos no host
      - PGID=1000  # Opcional
    ports:
      - "127.0.0.1:8081:8081"
    volumes:
      - ./tg-data:/var/lib/telegram-bot-api
      - ./uploads:/tmp/telegram-bot-api