name: Publish Docker Image

on:
  workflow_run:
    workflows: ["Build and Release"] # Nome do workflow do release.yml
    types:
      - completed
  workflow_dispatch: # Mantém manual para quando você quiser forçar

jobs:
  push_to_registry:
    # Só executa se o workflow de release terminou com SUCESSO
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Marcando com a tag v* ou latest
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/telegram-bot-api:latest