name: Build and Release Telegram Bot API

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Clonar o código-fonte oficial (já que ele não está no seu repo)
      - name: Clone Telegram Bot API Source
        run: |
          git clone --recursive https://github.com/tdlib/telegram-bot-api.git source
          
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install make git zlib1g-dev libssl-dev gperf cmake g++ -y

      # 2. Compilar a partir da pasta 'source'
      - name: Build Telegram Bot API
        run: |
          cd source
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local ..
          cmake --build . --target install -j$(nproc)

      - name: Prepare Artifact
        run: |
          mkdir -p dist
          cp /usr/local/bin/telegram-bot-api ./dist/
          cd dist
          tar -czvf telegram-bot-api-linux-amd64.tar.gz telegram-bot-api

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/telegram-bot-api-linux-amd64.tar.gz
          body: "Compilação automatizada (Ubuntu 24.04) otimizada com -O3."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}